In [168]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

In [102]:
df = pd.read_csv(r'C:\Users\Aditya\OneDrive - Manipal Academy of Higher Education\Desktop\SP\Manas\Datasets\weatherAUS.csv')

In [103]:
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [104]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [140]:
df.RainToday.unique()

array(['No', 'Yes'], dtype=object)

In [131]:
#df = df.replace({'RainToday': {'Yes': 1,'No': 0}}) 
                                
#df = df.replace({'RainTomorrow': {'Yes': 1,'No': 0}}) 
                                
#df.drop(df.index[df['RainToday'] == 12.19403438])
#df.dropna(subset = ['RainToday'])

df.drop(df[df['RainToday'] == 12.19403438096892].index, inplace = True)
df.drop(df[df['RainTomorrow'] == 12.19403438096892].index, inplace = True)


In [106]:
df = df.fillna(value=df['MinTemp'].mean())
df = df.fillna(value=df['MaxTemp'].mean())
df = df.fillna(value=df['Rainfall'].mean())
df = df.fillna(value=df['Evaporation'].mean())
df = df.fillna(value=df['Sunshine'].mean())
df = df.fillna(value=df['WindGustSpeed'].mean())
df = df.fillna(value=df['WindSpeed9am'].mean())
df = df.fillna(value=df['WindSpeed3pm'].mean())
df = df.fillna(value=df['Humidity9am'].mean())
df = df.fillna(value=df['Humidity3pm'].mean())
df = df.fillna(value=df['Pressure9am'].mean())
df = df.fillna(value=df['Pressure3pm'].mean())
df = df.fillna(value=df['Cloud9am'].mean())
df = df.fillna(value=df['Cloud3pm'].mean())
df = df.fillna(value=df['Temp9am'].mean())
df = df.fillna(value=df['Temp3pm'].mean())

In [107]:
df.drop('Date', inplace=True, axis=1)
df.drop('Location', inplace=True, axis=1)
df.drop('WindGustDir', inplace=True, axis=1)
df.drop('WindDir9am', inplace=True, axis=1)
df.drop('WindDir3pm', inplace=True, axis=1)

In [154]:
df= df.replace(to_replace ="Yes",value =1)
df =df.replace(to_replace ="No",value =0)

In [155]:
df.head()

MinTemp  MaxTemp  Rainfall  Evaporation   Sunshine  WindGustSpeed  \
0     13.4     22.9       0.6    12.194034  12.194034           44.0   
1      7.4     25.1       0.0    12.194034  12.194034           44.0   
2     12.9     25.7       0.0    12.194034  12.194034           46.0   
3      9.2     28.0       0.0    12.194034  12.194034           24.0   
4     17.5     32.3       1.0    12.194034  12.194034           41.0   

   WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0          20.0          24.0         71.0         22.0       1007.7   
1           4.0          22.0         44.0         25.0       1010.6   
2          19.0          26.0         38.0         30.0       1007.6   
3          11.0           9.0         45.0         16.0       1017.6   
4           7.0          20.0         82.0         33.0       1010.8   

   Pressure3pm   Cloud9am   Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.1   8.000000  12.194034     16.9     21.8          0   
1       1007.8  12.194034  12.194034     17.2     24.3          0   
2       1008.7  12.194034   2.000000     21.0     23.2          0   
3       1012.8  12.194034  12.194034     18.1     26.5          0   
4       1006.0   7.000000   8.000000     17.8     29.7          0   

   RainTomorrow  
0             0  
1             0  
2             0  
3             0  
4             0

In [156]:
df.isnull().sum()

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustSpeed    0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [157]:
df.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [158]:
X = df[['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday']]
y= df['RainTomorrow']

In [159]:
df.RainTomorrow.unique()

array([0, 1], dtype=int64)

In [160]:
dups = df.pivot_table(index = ['RainTomorrow'], aggfunc ='size')

In [161]:
dups

RainTomorrow
0    109586
1     31201
dtype: int64

In [162]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [163]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [164]:
predictions = dtree.predict(X_test)

In [165]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86     32826
           1       0.51      0.53      0.52      9411

    accuracy                           0.78     42237
   macro avg       0.69      0.69      0.69     42237
weighted avg       0.79      0.78      0.78     42237



In [166]:
print(confusion_matrix(y_test,predictions))

[[28095  4731]
 [ 4408  5003]]


In [170]:
rfc = RandomForestClassifier(n_estimators=300)

In [171]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=300)

In [172]:
predictions = rfc.predict(X_test)

In [173]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91     32826
           1       0.77      0.51      0.61      9411

    accuracy                           0.86     42237
   macro avg       0.82      0.73      0.76     42237
weighted avg       0.85      0.86      0.85     42237



In [174]:
print(confusion_matrix(y_test,predictions))

[[31400  1426]
 [ 4603  4808]]
